elevation_platform_node:
  ros__parameters:
    sim: False

/elevation_joint_1/joint_motor_driver_node:
  ros__parameters:
    can_id: 0x60
    gear_ratio: 88.0

/elevation_joint_2/joint_motor_driver_node:
  ros__parameters:
    can_id: 0x61
    gear_ratio: 88.0

/elevation_joint_3/joint_motor_driver_node:
  ros__parameters:
    can_id: 0x62
    gear_ratio: 88.0

/elevation_joint_4/joint_motor_driver_node:
  ros__parameters:
    can_id: 0x63
    gear_ratio: 108.0